### ISSUE TITLE
Front End Web Development Track Courses to be Completed

### ISSUE THREAD

**Issue by zacharyMatthewstearn** [zacharyMatthewstearn/Treehouse#2]
## TODO

*Courses left to complete in the Treehouse Front End Web Development Track*

* [ ] How to Make a Website
* [ ] CSS Basics
* [ ] JavaScript Basics
* [ ] CSS Layout Basics
* [ ] Responsive Layouts
* [ ] CSS Flexbox Layout
* [ ] HTML Forms
* [ ] JavaScript Loops, Arrays, and Objects
* [ ] CSS Selectors
* [ ] jQuery Basics
* [ ] Bootstrap4 Basics
* [ ] HTML Tables
* [ ] Interactive Web Pages with JavaScript
* [ ] HTML Video and Audio
* [ ] AJAX Basics
* [ ] Object-Oriented JavaScript
* [ ] Accessibility
* [ ] Website Optimization
* [ ] Console Foundations
* [ ] Git Basics
* [ ] Front End Performance Optimization

:tada: :ok_woman: :confetti_ball:
